#!/bin/bash
set -eux

mkdir -p ./example/out

protoc \
    --proto_path=./example/ \
    --php_out=./example/out \
    --grpc_out=./example/out/ \
    --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin \
    --php-grpc_out=./example/out/  \
    ./example/helloworld.proto

exit

protoc \
    --proto_path=./example/ \
    --php_out=example/out \
    --php-grpc_out=./example/out/  \
    --grpc_out=./example/out/ \
    ./example/helloworld.proto

//--plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin \

#protoc \
#    --proto_path=./example/ \
#    --php_out=example/out \
#    --php-grpc_out=./example/out/  \
#    --grpc_out=./example/out/ \
#    --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin \
#    ./example/helloworld.proto
